In [1]:
from IPython.display import HTML
HTML ('<iframe src=http://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data width=300 height=200></iframe')


In [3]:
from sklearn.datasets import load_iris
iris=load_iris()
x=iris.data
y=iris.target

In [5]:
print (x.shape)
print (y.shape)

(150, 4)
(150,)


In [7]:
from sklearn.neighbors import KNeighborsClassifier

In [9]:
knn=KNeighborsClassifier(n_neighbors=1)

In [10]:
print (knn)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=1, p=2,
           weights='uniform')


In [11]:
knn.fit(x, y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=1, p=2,
           weights='uniform')

In [13]:
knn.predict([3, 5, 4, 2])


c:\users\lisa\appdata\local\programs\python\python35-32\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([2])

In [14]:
knn=KNeighborsClassifier(n_neighbors=5)
knn.fit(x, y)
knn.predict([3, 5, 4, 2])

c:\users\lisa\appdata\local\programs\python\python35-32\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([1])

In [15]:
from sklearn.linear_model import LogisticRegression
logreg=LogisticRegression()
logreg.fit(x, y)
logreg.predict([3, 5, 4, 2])

c:\users\lisa\appdata\local\programs\python\python35-32\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([2])